custom:
  app:
    super-admin-role-id: 1
    default-role-id: 2
    default-dept-id: 6
    avatar-postfix: ".png,.jpg,.jpeg"
    avatar-path: "img/avatar"
  minio:
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: mall
  token:
    # token存储的请求头
    token-header: Authorization
    # token加解密使用的密钥
    secret: ling-admin-secret
    # token的超期限时间
    expiration: 720
    # token开头
    token-prefix: 'Bearer '
    # token中储存的uuid键名
    user-key: login_user_key
  wx:
    app-id:
    app-secret:
  # 需要忽略的请求
  ignores:
    get:
      - "/swagger-ui/**"
      - "/swagger-resources/**"
      - "/*/api-docs"
    # 需要忽略的 post 请求
    post:
      - "/login"
      - "/error"
    # 需要忽略的请求，不限方法
    pattern:
      - "/ws/**"

spring:
  application:
    name: ling-admin
  profiles:
    # 区分配置,这里使用开发时配置(application-dev.yml)
    active: dev
    include: socket,mp
  servlet:
    multipart:
      # 开启文件上传
      enabled: true
      # 单个上传文件最大值
      max-file-size: 200MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

